### PR TITLE
feat: xArmAPI daemonization with gRPC

### LINKED ISSUE #5: C++: Disable console output of xArm SDK
In order to use the CLI tool with other frameworks/languages (e.g. Nodejs) the output of the xArm SDK must be disabled/formatted. In the best case, this complies with the setting for multi-level logging, which is determined by the flags. (see issue #4)

### LINKED ISSUE #18: Daemonization of Modbus/TCP connection manager
Once we find a way to daemonize the xArm connection handler, we will implement `server` command to start establishing the connection with an xArm robot.

### LINKED ISSUE #31: Autogenerate Makefile with cmake
For linking generated gRPC sources with xarm-commander, it's better to use cmake.

### PR DESCRIPTION
**Pull request by iomz**
This (somewhat destructive) PR implements #18 
As updated in README.md, xarm-commander now interacts with a new program "xarm-daemon" to run commands via its `xArmAPI` object.

In addition, the following changes were made:
- add a new submodule: https://github.com/fmtlib/fmt
- build with CMake
- comment out the existing subcommand and re-implemented only `get_version()`
- filter logs through gRPC (related to #17 and #23)

Resolves #5 
Resolves #18 
Resolves #31

### CODE REVIEW

**Comment by iomz** [comment]
Ha! Passed the check. Calling it a day.

**Comment by jo-bru** [comment]
Oh wow, that's a lot!:sweat_smile:
Thank you very much!
I've tried to get it to work on my system but have not yet succeeded (some building errors). I'll first focus on the mid-term presentation and then try to make it work.

About the system structure:
I like the usage of gRPC for internal communication, but I guess we could then directly send the commands from the Servient implementation (`nodewot-xarm`) to the connection manager (`xarm-deamon`) (i.e. the Servient implements the gRPC client).
In this case, we would not need to include the `xarm-commander` in the software stack and don't need to start a separate `childProcess` for each command.
The `xarm-commander` might be still interesting as a low-layer/ non-WoT API.
Does this make sense?

**Comment by iomz** [comment]
> I've tried to get it to work on my system but have not yet succeeded (some building errors).

I'm interested in your building errors. Can you share the problem? I might be able to solve it rather quickly – I've seen it all yesterday all day long lol

> I'll first focus on the mid-term presentation and then try to make it work.

Yes, please do so.

> About the system structure: I like the usage of gRPC for internal communication, but I guess we could then directly send the commands from the Servient implementation (`nodewot-xarm`) to the connection manager (`xarm-deamon`) (i.e. the Servient implements the gRPC client). In this case, we would not need to include the `xarm-commander` in the software stack and don't need to start a separate `childProcess` for each command. The `xarm-commander` might be still interesting as a low-layer/ non-WoT API. Does this make sense?

That's indeed a great and more interesting idea than the Servient as just a shell executor (which I initially accused of the abuse but somehow supported later). I was too narrow-sighted and didn't realize what I did. Let's steer to this direction 😄 
However, the xarm-commander program still serves two additional values: 1. driver for developing and testing the gRPC service itself and 2. tool for the latency measurement.

**Comment by jo-bru** [comment]
> I'm interested in your building errors. Can you share the problem? I might be able to solve it rather quickly – I've seen it all yesterday all day long lol  

Now the gRPC build process somehow worked, but when I try to build the `xarm-commander` and `xarm-deamon` as described [here](https://github.com/Interactions-HSG/xarm-commander/tree/feat/xarm-api-daemon#build-xarm-daemon-and-xarm-commander) I get the following error:
`error while loading shared libraries: libgrpc_plugin_support.so.1.41: cannot open shared object file: No such file or directory`

For the gRPC installation, I had to add the `-DBUILD_SHARED_LIBS=ON` option. I'm not sure if that was the right way..

**Comment by jo-bru** [comment]
>That's indeed a great and more interesting idea than the Servient as just a shell executor (which I initially accused of the abuse but somehow supported later). I was too narrow-sighted and didn't realize what I did. Let's steer to the direction with gRPC😄
However, the xarm-commander program still serves two additional values: 1. driver for developing and testing the gRPC service itself and 2. tool for the latency measurement.

Great, I'll also briefly discuss this in the mid-term presentation.

**Comment by jo-bru** [comment]
> Nice, it works. It took around 30ms to get the version, when running it locally from Basel 

Just tested it locally on nano: seems to take exactly 19ms when executing `time xarm-commander get_version`

**Pull request merged**
