### PR TITLE
feat(examples): add examples for bash and nodejs 

### LINKED ISSUE #6: Create example scripts in Nodejs to use the xarm-commander
To test the usefulness of the xarm-commander tool, create some example scripts that execute a few commands using the CLI tool.

### PR DESCRIPTION
**Pull request by jo-bru**
These are only some simple examples of how the xarm-commander can be integrated/used from other languages.
The following examples are implemented:

- `bash_routine.sh`: A simple collection of commands called from a bash script.
- `node_async.js`: Integration into Javascript using async functions.
- `node_promise.js`: Integration into Javascript using promises.

A proper error handling and proper logging/responses have to be implemented in the future (Issues #26 and #17).

The response syntax will be further adjusted while implementing the node-wot servient.

Closes #6

### CODE REVIEW

**Comment by iomz** [comment]
Can I have a look on the weekend?

**Comment by jo-bru** [comment]
Sure, no rush! :)

**Comment by iomz** [comment]
Ok thanks 😄  I will try not to prolong beyond Monday, then...

**Review by iomz — CHANGES_REQUESTED** [review]
Cool!
Can you provide commands to run the .js examples in `README.md`?
Also, would you remove the hardcoded IP address from the .js files? I did it for .sh.

**Comment by jo-bru** [comment]
Thanks!
Like that?

**Review by iomz — APPROVED** [review]
Precisely, thank you @jo-bru !

**Pull request merged**
